apiVersion: 1

datasources:
  # ─── Prometheus ──────────────────────────────────────────────────────────────
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo

  # ─── Loki ────────────────────────────────────────────────────────────────────
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"traceId":"(\w+)"'
          name: TraceID
          url: '$${__value.raw}'
          urlDisplayLabel: View Trace in Tempo

  # ─── Tempo ───────────────────────────────────────────────────────────────────
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: '-30m'
        spanEndTimeShift: '30m'
      spanBar:
        type: Tag
        tag: http.url
      lokiSearch:
        datasourceUid: loki

  # ─── Pyroscope ───────────────────────────────────────────────────────────────
  - name: Pyroscope
    type: grafana-pyroscope-datasource
    uid: pyroscope
    access: proxy
    url: http://pyroscope:4040
    jsonData:
      minStep: "15s"
